//! 域错误类型。全链路带 context；API key 永不进入错误信息。

use std::path::PathBuf;

pub type Result<T> = std::result::Result<T, Error>;

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("{context}: {source}")]
    Io {
        context: String,
        #[source]
        source: std::io::Error,
    },

    #[error(
        "invalid JSON in {}: {source}\n  donn never overwrites a broken file; fix it by hand (donn regenerates its own keys on next sync)",
        path.display()
    )]
    InvalidJson {
        path: PathBuf,
        #[source]
        source: serde_json::Error,
    },

    #[error("invalid TOML in {}: {message}", path.display())]
    InvalidToml { path: PathBuf, message: String },

    #[error("profile '{name}' not found{}", format_available(available))]
    ProfileNotFound {
        name: String,
        available: Vec<String>,
    },

    #[error("profile '{0}' already exists; pick another name or remove it first (donn → d)")]
    ProfileExists(String),

    #[error(
        "invalid profile/alias name '{0}': must match [a-z][a-z0-9-]* (lowercase letter first, then lowercase letters, digits or '-')"
    )]
    InvalidName(String),

    #[error("preset '{0}' not found; run `donn` and press `a` to pick a provider from the list")]
    PresetNotFound(String),

    #[error(
        "claude binary not found; install Claude Code or set claude_bin in ~/.donn/config.toml"
    )]
    ClaudeNotFound,

    #[error("command name '{0}' conflicts with an existing command at {1}; choose another alias")]
    AliasConflict(String, PathBuf),

    #[error("refusing to touch {}: file was not generated by donn", .0.display())]
    NotOwnedByDonn(PathBuf),

    #[error("profile '{0}' appears to have a running session; close it first (checked via lsof)")]
    ProfileInUse(String),

    #[error("alias '{alias}' is already used by profile '{profile}' ({}); pick another name", .path.display())]
    AliasInUse {
        alias: String,
        profile: String,
        path: PathBuf,
    },

    /// 用户输入或配置值未通过校验（表单值、键名、配置项）。
    #[error("{0}")]
    InvalidInput(String),

    /// 现有文件的 JSON 容器被手改成错误类型，donn 拒绝合并（绝不静默清空重建）。
    #[error("cannot merge {what}: expected {expected}, found {found}; fix the file by hand")]
    NotMergeable {
        what: String,
        expected: &'static str,
        found: &'static str,
    },

    /// 环境或内部异常（home 目录不可知、路径异常、序列化失败等）。
    #[error("{0}")]
    Internal(String),
}

fn format_available(available: &[String]) -> String {
    if available.is_empty() {
        String::from("; no profiles exist yet — run `donn` to create one")
    } else {
        format!("; available: {}", available.join(", "))
    }
}

/// `map_err` 辅助：给 io::Error 加上下文。
pub fn io_ctx(context: impl Into<String>) -> impl FnOnce(std::io::Error) -> Error {
    let context = context.into();
    move |source| Error::Io { context, source }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn profile_not_found_lists_available() {
        let err = Error::ProfileNotFound {
            name: "zai".into(),
            available: vec!["kimi".into(), "official".into()],
        };
        let msg = err.to_string();
        assert!(msg.contains("kimi, official"), "{msg}");

        let err = Error::ProfileNotFound {
            name: "zai".into(),
            available: vec![],
        };
        assert!(err.to_string().contains("no profiles exist yet"));
    }
}
