//! bin wrapper 生成：profile 名即命令名。
//! wrapper 纯委托回 donn 本体，逻辑不复制，升级 donn 即升级所有 wrapper。

use std::path::{Path, PathBuf};

use crate::error::{Error, Result, io_ctx};
use crate::fsx;
use crate::home::validate_name;

/// 首行标记：doctor/删除据此识别归属，绝不删除非 donn 生成的同名文件。
pub const OWNERSHIP_MARK: &str = "generated by donn";

/// 与 claude / donn 本体冲突的保留名。
const RESERVED_NAMES: &[&str] = &["claude", "donn"];

/// wrapper 文件路径（Windows 加 `.cmd` 后缀）。
pub fn wrapper_path(bin_dir: &Path, alias: &str) -> PathBuf {
    if cfg!(windows) {
        bin_dir.join(format!("{alias}.cmd"))
    } else {
        bin_dir.join(alias)
    }
}

/// PATH 冲突检查：保留名拒绝；PATH 上已有非 donn 同名命令 → 拒绝并给出路径；
/// 已被**其它 profile** 的 donn wrapper 占用 → 拒绝（绝不静默覆盖）；
/// 指向 `for_profile` 自身的 wrapper 允许覆盖（重建场景）。
pub fn check_alias_conflict(bin_dir: &Path, alias: &str, for_profile: &str) -> Result<()> {
    validate_name(alias)?;
    if RESERVED_NAMES.contains(&alias) {
        return Err(Error::AliasConflict(
            alias.to_string(),
            PathBuf::from("<reserved>"),
        ));
    }

    let ours = wrapper_path(bin_dir, alias);
    let mut candidates: Vec<PathBuf> = Vec::new();
    if ours.exists() {
        candidates.push(ours.clone());
    }
    if let Ok(found) = which::which(alias)
        && found != ours
    {
        candidates.push(found);
    }
    for path in candidates {
        // 读不了候选文件（权限/IO）直接报 IO 错误，不猜测归属
        if !is_donn_wrapper(&path)? {
            return Err(Error::AliasConflict(alias.to_string(), path));
        }
        match wrapper_target(&path)? {
            Some(target) if target == for_profile => {}
            Some(target) => {
                return Err(Error::AliasInUse {
                    alias: alias.to_string(),
                    profile: target,
                    path,
                });
            }
            None => return Err(Error::AliasConflict(alias.to_string(), path)),
        }
    }
    Ok(())
}

/// 生成 wrapper。`donn_exe` 为创建时的 donn 绝对路径；
/// 文件不存在或已损坏时脚本内退回 `command -v donn`。
pub fn generate(bin_dir: &Path, alias: &str, profile: &str, donn_exe: &Path) -> Result<PathBuf> {
    validate_name(alias)?;
    let path = wrapper_path(bin_dir, alias);
    if path.exists() && !is_donn_wrapper(&path)? {
        return Err(Error::NotOwnedByDonn(path));
    }

    let content = if cfg!(windows) {
        format!(
            "@echo off\r\nrem {OWNERSHIP_MARK} \u{2014} do not edit\r\n\"{}\" run {profile} -- %*\r\n",
            donn_exe.display()
        )
    } else {
        let executable = donn_exe.to_str().ok_or_else(|| {
            Error::InvalidInput(format!(
                "donn executable path is not valid UTF-8: {}",
                donn_exe.display()
            ))
        })?;
        let executable = shlex::try_quote(executable).map_err(|error| {
            Error::InvalidInput(format!(
                "donn executable path cannot be represented in a shell wrapper: {error}"
            ))
        })?;
        format!(
            r#"#!/bin/sh
# {OWNERSHIP_MARK} — do not edit
DONN={executable}
[ -x "$DONN" ] || DONN="$(command -v donn)" || {{ echo "donn not found; reinstall donn or run: donn doctor" >&2; exit 127; }}
exec "$DONN" run {profile} -- "$@"
"#
        )
    };

    fsx::write_atomic(&path, content.as_bytes())?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))
            .map_err(io_ctx(format!("failed to chmod {}", path.display())))?;
    }

    Ok(path)
}

/// 删除属于指定 profile 的 wrapper。不存在视为成功；即使 spec 被手改，
/// 也绝不删除其它 profile 的同名 wrapper。
pub fn remove(bin_dir: &Path, alias: &str, expected_profile: &str) -> Result<()> {
    let path = wrapper_path(bin_dir, alias);
    if !path.exists() {
        return Ok(());
    }
    if !is_donn_wrapper(&path)? {
        return Err(Error::NotOwnedByDonn(path));
    }
    match wrapper_target(&path)? {
        Some(target) if target == expected_profile => {}
        Some(profile) => {
            return Err(Error::AliasInUse {
                alias: alias.to_string(),
                profile,
                path,
            });
        }
        None => return Err(Error::AliasConflict(alias.to_string(), path)),
    }
    std::fs::remove_file(&path).map_err(io_ctx(format!("failed to remove {}", path.display())))
}

/// 判断文件是否由 donn 生成（前两行内含标记）。
/// IO 错误（权限等）传播给调用方；非 UTF-8 内容（同名二进制）= 不是 donn wrapper。
pub fn is_donn_wrapper(path: &Path) -> Result<bool> {
    let text = read_lossy(path)?;
    Ok(text
        .lines()
        .take(2)
        .any(|line| line.contains(OWNERSHIP_MARK)))
}

/// wrapper 指向的 profile 名。只认 [`generate`] 产出的完整启动行，路径里的
/// ` run ` 等文本不得被误当成 profile。
pub fn wrapper_target(path: &Path) -> Result<Option<String>> {
    let pattern =
        regex::Regex::new(r#"^(?:exec "\$DONN"|"[^"]+") run ([a-z][a-z0-9-]*) -- (?:"\$@"|%\*)$"#)
            .map_err(|e| Error::Internal(format!("invalid wrapper launch-line regex: {e}")))?;
    let text = read_lossy(path)?;
    for line in text.lines() {
        if let Some(captures) = pattern.captures(line.trim_end()) {
            return Ok(Some(captures[1].to_string()));
        }
    }
    Ok(None)
}

/// 按文本读取（lossy）：IO 错误传播，二进制内容不报错——归属判断只看文本标记。
fn read_lossy(path: &Path) -> Result<String> {
    let bytes =
        std::fs::read(path).map_err(io_ctx(format!("failed to read {}", path.display())))?;
    Ok(String::from_utf8_lossy(&bytes).into_owned())
}

/// bin_dir 是否在 PATH 中（完成页/doctor 提示用）。
pub fn bin_dir_in_path(bin_dir: &Path) -> bool {
    let Some(path_var) = std::env::var_os("PATH") else {
        return false;
    };
    let Ok(target) = std::path::absolute(bin_dir) else {
        return false;
    };
    std::env::split_paths(&path_var)
        .filter(|path| !path.as_os_str().is_empty())
        .any(|path| std::path::absolute(path).is_ok_and(|candidate| candidate == target))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn generate_and_inspect() {
        let dir = TempDir::new().unwrap();
        let bin = dir.path().join("bin");
        let path = generate(&bin, "zai", "zai", Path::new("/usr/local/bin/donn")).unwrap();
        assert!(path.exists());
        assert!(is_donn_wrapper(&path).unwrap());
        assert_eq!(wrapper_target(&path).unwrap().as_deref(), Some("zai"));
        let text = std::fs::read_to_string(&path).unwrap();
        assert!(text.contains("run zai"));
        assert!(text.contains("/usr/local/bin/donn"));
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&path).unwrap().permissions().mode();
            assert_eq!(mode & 0o777, 0o755);
        }
    }

    #[cfg(unix)]
    #[test]
    fn generated_wrapper_shell_quotes_executable_path_and_arguments() {
        use std::os::unix::fs::PermissionsExt;

        let dir = TempDir::new().unwrap();
        let executable = dir.path().join("donn '$USER with spaces");
        std::fs::write(&executable, "#!/bin/sh\nprintf '%s\\n' \"$@\"\n").unwrap();
        std::fs::set_permissions(&executable, std::fs::Permissions::from_mode(0o755)).unwrap();
        let wrapper = generate(dir.path(), "safe", "profile-a", &executable).unwrap();

        let output = std::process::Command::new(wrapper)
            .arg("argument with spaces")
            .output()
            .unwrap();
        assert!(output.status.success());
        assert_eq!(
            String::from_utf8(output.stdout).unwrap(),
            "run\nprofile-a\n--\nargument with spaces\n"
        );
    }

    #[test]
    fn executable_path_containing_run_does_not_fool_target_parser() {
        let dir = TempDir::new().unwrap();
        let executable = dir.path().join("a run b").join("donn");
        let wrapper = generate(dir.path(), "runny", "runny", &executable).unwrap();
        assert_eq!(wrapper_target(&wrapper).unwrap().as_deref(), Some("runny"));

        std::fs::write(
            &wrapper,
            "#!/bin/sh\n# generated by donn — do not edit\necho something run wrong -- else\n",
        )
        .unwrap();
        assert_eq!(wrapper_target(&wrapper).unwrap(), None);
    }

    #[test]
    fn never_touch_foreign_files() {
        let dir = TempDir::new().unwrap();
        let bin = dir.path().to_path_buf();
        let foreign = wrapper_path(&bin, "mytool");
        std::fs::write(&foreign, "#!/bin/sh\necho user script\n").unwrap();
        assert!(matches!(
            generate(&bin, "mytool", "p", Path::new("/x/donn")),
            Err(Error::NotOwnedByDonn(_))
        ));
        assert!(matches!(
            remove(&bin, "mytool", "p"),
            Err(Error::NotOwnedByDonn(_))
        ));
        assert!(foreign.exists(), "用户文件原样保留");
    }

    #[test]
    fn remove_missing_is_ok_and_owned_is_deleted() {
        let dir = TempDir::new().unwrap();
        let bin = dir.path().to_path_buf();
        remove(&bin, "ghost", "ghost").unwrap();
        let path = generate(&bin, "zai", "zai", Path::new("/x/donn")).unwrap();
        remove(&bin, "zai", "zai").unwrap();
        assert!(!path.exists());
    }

    #[test]
    fn remove_never_deletes_another_profiles_wrapper() {
        let dir = TempDir::new().unwrap();
        let bin = dir.path().to_path_buf();
        let path = generate(&bin, "shared", "profile-a", Path::new("/x/donn")).unwrap();

        let err = remove(&bin, "shared", "profile-b").unwrap_err();
        assert!(matches!(
            err,
            Error::AliasInUse { ref profile, .. } if profile == "profile-a"
        ));
        assert!(
            path.exists(),
            "another profile's wrapper must remain untouched"
        );
    }

    #[test]
    fn reserved_and_invalid_aliases_rejected() {
        let dir = TempDir::new().unwrap();
        for name in ["claude", "donn"] {
            assert!(
                matches!(
                    check_alias_conflict(dir.path(), name, "p"),
                    Err(Error::AliasConflict(..))
                ),
                "{name}"
            );
        }
        assert!(matches!(
            check_alias_conflict(dir.path(), "Bad_Name", "p"),
            Err(Error::InvalidName(_))
        ));
    }

    #[test]
    fn conflict_with_existing_command_on_path() {
        // "sh" 几乎必然存在于 PATH
        let dir = TempDir::new().unwrap();
        let err = check_alias_conflict(dir.path(), "sh", "p").unwrap_err();
        assert!(matches!(err, Error::AliasConflict(..)), "{err}");
    }

    #[test]
    fn alias_owned_by_another_profile_rejected() {
        let dir = TempDir::new().unwrap();
        let bin = dir.path().to_path_buf();
        generate(&bin, "z", "profile-a", Path::new("/x/donn")).unwrap();

        // 其它 profile 想占用 → 结构化拒绝，错误携带占用者
        let err = check_alias_conflict(&bin, "z", "profile-b").unwrap_err();
        assert!(
            matches!(&err, Error::AliasInUse { profile, .. } if profile == "profile-a"),
            "{err}"
        );
        assert!(err.to_string().contains("profile-a"), "{err}");
        // 同一 profile 重建 → 允许覆盖
        check_alias_conflict(&bin, "z", "profile-a").unwrap();
        // 非 donn 文件 → AliasConflict
        std::fs::write(wrapper_path(&bin, "u"), "#!/bin/sh\nuser\n").unwrap();
        assert!(matches!(
            check_alias_conflict(&bin, "u", "profile-a"),
            Err(Error::AliasConflict(..))
        ));
    }
}
